name: deploy-postgrades1

on:
  push:
    branches: ["master"]

jobs:
  deploy-mysql-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: echo 'hello world ...'
      - run: ls -la
      
      - run: touch .env
      - run: echo 'DEV_DATABASE_URL=${{secrets.PG_CONN}}' >> .env
      - run: cat .env

      - run: npm install 

      - run: npm install -g sequelize-cli

      - run: sequelize db:migrate

      - run: docker build -t pedrogarpad/postgres-api-videojuegos:${{github.sha}} .

      - run: docker images

      - run: docker run --name api-post-LA -p 8000:8000 -d pedrogarpad/postgres-api-videojuegos:${{github.sha}}

      - run: docker ps

      - run: docker exec api-post-LA ls -la


      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER}}/postgres-api-videojuegos:${{github.sha}}
